---
title: "Data Model"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    toc_depth: 3
    self_contained: false
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```


 ```{css}
 h1 {color: #0056b8}
 h2 {color: #0056b8}
 h3 {color: #2387fa}
 .list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover 
 
#TOC ul,
#TOC li,
#TOC span,
#TOC a {
  margin: 0;
  padding: 0;
  position: relative;
}
#TOC {
  line-height: 1;
  border-radius: 5px 5px 0 0;
  background: #141414;
  background: linear-gradient(to bottom, #333333 0%, #141414 100%);
  border-bottom: 2px solid #0fa1e0;
  width: auto;
}
#TOC:after,
#TOC ul:after {
  content: '';
  display: block;
  clear: both;
}
#TOC a {
  background: #141414;
  background: linear-gradient(to bottom, #333333 0%, #141414 100%);
  color: #ffffff;
  display: block;
  padding: 19px 20px;
  text-decoration: none;
  text-shadow: none;
}
#TOC ul {
  list-style: none;
}
#TOC > ul > li {
  display: inline-block;
  float: left;
  margin: 0;
}
#TOC > ul > li > a {
  color: #ffffff;
}
#TOC > ul > li:hover:after {
  content: '';
  display: block;
  width: 0;
  height: 0;
  position: absolute;
  left: 50%;
  bottom: 0;
  border-left: 10px solid transparent;
  border-right: 10px solid transparent;
  border-bottom: 10px solid #0fa1e0;
  margin-left: -10px;
}
#TOC > ul > li:first-child > a {
  border-radius: 5px 0 0 0;
}
#TOC.align-right > ul > li:first-child > a,
#TOC.align-center > ul > li:first-child > a {
  border-radius: 0;
}
#TOC.align-right > ul > li:last-child > a {
  border-radius: 0 5px 0 0;
}
#TOC > ul > li.active > a,
#TOC > ul > li:hover > a {
  color: #ffffff;
  box-shadow: inset 0 0 3px #000000;
  background: #070707;
  background: linear-gradient(to bottom, #262626 0%, #070707 100%);
}
#TOC .has-sub {
  z-index: 1;
}
#TOC .has-sub:hover > ul {
  display: block;
}
#TOC .has-sub ul {
  display: none;
  position: absolute;
  width: 200px;
  top: 100%;
  left: 0;
}
#TOC .has-sub ul li a {
  background: #0fa1e0;
  border-bottom: 1px dotted #31b7f1;
  filter: none;
  display: block;
  line-height: 120%;
  padding: 10px;
  color: #ffffff;
}
#TOC .has-sub ul li:hover a {
  background: #0c7fb0;
}
#TOC ul ul li:hover > a {
  color: #ffffff;
}
#TOC .has-sub .has-sub:hover > ul {
  display: block;
}
#TOC .has-sub .has-sub ul {
  display: none;
  position: absolute;
  left: 100%;
  top: 0;
}
#TOC .has-sub .has-sub ul li a {
  background: #0c7fb0;
  border-bottom: 1px dotted #31b7f1;
}
#TOC .has-sub .has-sub ul li a:hover {
  background: #0a6d98;
}
#TOC ul ul li.last > a,
#TOC ul ul li:last-child > a,
#TOC ul ul ul li.last > a,
#TOC ul ul ul li:last-child > a,
#TOC .has-sub ul li:last-child > a,
#TOC .has-sub ul li.last > a {
  border-bottom: 0;
}
#TOC ul {
  font-size: 1.2rem;
}
 ```



```{r import_file, include=FALSE}
Description <- read_excel(paste0(dirinput, "Data_Model_1.xlsx"), sheet = "Description", col_names = FALSE)
DM1 <- read_excel(paste0(dirinput, "Data_Model_1.xlsx"), sheet = "table1")
DM2 <- read_excel(paste0(dirinput, "Data_Model_1.xlsx"), sheet = "table2")
DM3 <- read_excel(paste0(dirinput, "Data_Model_1.xlsx"), sheet = "table3")
```

<br>

# Introduction 

---

<br>

# First group of DM 

---

<br>

## `r Description[1,1]` 

`r Description[1,2]`

```{r display_table1}
paged_table(DM1)
```

<br> 


# Second group of DM

---

<br>

## `r Description[2,1]`

`r Description[2,2]`

```{r display_table2}
datatable(DM2)
```

<br><br>

## `r Description[3,1]`

`r Description[3,2]`

```{r display_table3}
kbl(DM2) %>%
  add_header_above() %>%
  kable_paper() %>%
  scroll_box(width = "100%", height = "400px") #width = "100%", height = "400px"
```